<?php

namespace WP\TournamentBundle\Repository;

/**
 * NomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomRepository extends \Doctrine\ORM\EntityRepository
{
}
